#!/bin/bash
#
# Small script to show what flags hopper requires.
#

# clang-15
CC="clang"
CXX="clang++"

# Symbols, ASAN, Edge Coverage
CFLAGS=" -g -O0
         -fsanitize=address
         -fno-omit-frame-pointer
         -fsanitize-coverage=edge,trace-pc-guard
         -o target"
 
$CC $CFLAGS $1

