schema = 3

[mod]
  [mod."github.com/aymanbagabas/go-osc52"]
    version = "v1.0.3"
    hash = "sha256-+PPvxpq4eEcolG77a9g3r5Tw67Zs7hDOXS3nOYnizBQ="
  [mod."github.com/bits-and-blooms/bitset"]
    version = "v1.5.0"
    hash = "sha256-f9sazJLhiMFnxAGM/9TmgRbNyoAt+nWlouqlh0BmJy8="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v0.23.1"
    hash = "sha256-1IaqhHYazhCnnU2UVNFBcc/WOfKnv6UTb+eudOFV4ZU="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.6.0"
    hash = "sha256-etQYdwy833o3Tp5zIatq0C6UFpInD2Fwk/WH8AtHRaY="
  [mod."github.com/containerd/console"]
    version = "v1.0.3"
    hash = "sha256-4p4u/rS7G4KKbIcZaVMqE1OtSoNlOpmcYFwO0ZEH/V0="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.16"
    hash = "sha256-YMaPZvShDfA98vqw1+zWWl7M1IT4nHPGBrAt7kHo8Iw="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.14"
    hash = "sha256-O3QdxqAcJgQ+HL1v8oBA4iKBwJ2AlDN+F464027hWMU="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20211018074035-2e021307bc4b"
    hash = "sha256-v4zQmLl5Z6hoKtuH0Ry6hRwAKNWna4rXirK62LXNvbY="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.13.0"
    hash = "sha256-0KO2SSfj4J6Q3rXMohV+hnncUHiY7nAWU8hUbDQkLHA="
  [mod."github.com/rivo/uniseg"]
    version = "v0.2.0"
    hash = "sha256-GLj0jiGrT03Ept4V6FXCN1yeZ/b6PpS3MEXK6rYQ8Eg="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220811171246-fbc7d0a398ab"
    hash = "sha256-acnc9aKY/SyebObLasV+gowfB0S+6ehz3hnUgAmQmSU="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210927222741-03fcf44c2211"
    hash = "sha256-DsX2xay7Y/0/bikp4vU8ArF0B6KHyqEc37PwgvmjhSs="
  [mod."golang.org/x/text"]
    version = "v0.3.8"
    hash = "sha256-KKHU0OMfT4oxTIzIVqan8MY8wNvgBW00s24hF+kWbMA="
